"""Interactive FYERS OAuth token setup; writes secrets only to Dependencies/.env.

Run outside market hours. Never paste API secrets or access tokens into chat or
commit a populated .env file.
"""
from __future__ import annotations

import os
import sys
import webbrowser
from pathlib import Path

from dotenv import dotenv_values
from fyers_apiv3 import fyersModel

ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / "Dependencies" / ".env"

def main() -> int:
    current = dotenv_values(ENV_PATH) if ENV_PATH.exists() else {}
    app_id = os.getenv("FYERS_APP_ID") or str(current.get("FYERS_APP_ID") or "").strip()
    secret = os.getenv("FYERS_API_SECRET") or str(current.get("FYERS_API_SECRET") or "").strip()
    redirect = os.getenv("FYERS_REDIRECT_URI") or str(current.get("FYERS_REDIRECT_URI") or "http://127.0.0.1:8080/").strip()
    if not app_id or not secret:
        print("Set FYERS_APP_ID and FYERS_API_SECRET in Dependencies/.env first.", file=sys.stderr)
        return 2
    session = fyersModel.SessionModel(
        client_id=app_id, secret_key=secret, redirect_uri=redirect,
        response_type="code", grant_type="authorization_code"
    )
    url = session.generate_authcode()
    print("Open this FYERS login URL and approve the app:")
    print(url)
    try:
        webbrowser.open(url)
    except Exception:
        pass
    code = input("Paste the authorization code (or redirected URL): ").strip()
    if "auth_code=" in code:
        from urllib.parse import parse_qs, urlparse
        code = parse_qs(urlparse(code).query).get("auth_code", [""])[0]
    if not code:
        print("No authorization code supplied.", file=sys.stderr)
        return 2
    session.set_token(code)
    result = session.generate_token()
    if not isinstance(result, dict) or str(result.get("s", "")).lower() != "ok" or not result.get("access_token"):
        print(f"FYERS token exchange failed: {result!r}", file=sys.stderr)
        return 1
    access = str(result["access_token"])
    # Preserve comments and unrelated keys. Replace only FYERS_ACCESS_TOKEN.
    lines = ENV_PATH.read_text(encoding="utf-8").splitlines() if ENV_PATH.exists() else []
    key_line = "FYERS_ACCESS_TOKEN="
    output, replaced = [], False
    for line in lines:
        if line.startswith("FYERS_ACCESS_TOKEN="):
            output.append(key_line + access)
            replaced = True
        else:
            output.append(line)
    if not replaced:
        output.extend(["", "# FYERS access token generated by fyers_token_setup.py", key_line + access])
    ENV_PATH.parent.mkdir(parents=True, exist_ok=True)
    ENV_PATH.write_text("\n".join(output) + "\n", encoding="utf-8")
    print(f"Saved FYERS_ACCESS_TOKEN to {ENV_PATH}. Token value not displayed.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
